### PR TITLE
[READY] Challenge Implementation

### PR DESCRIPTION
**Pull request by jpagex**
Hello, thank you for this amazing challenge. Here is my version which is READY.

I have not seen an open position in engineering on your website, but let me know if you have any, I am interested. You can go to my website to check my resume: [https://www.jeremypage.me](https://www.jeremypage.me).

I have included `shell.nix` which should provides the development tools I used. Just run `./start.sh` to launch the application. If you don't have Nix, the requirements are `elm-live` and `elm` (available on your path). Otherwise, just compile `src/Main.elm` into `main.js` and use `index.html`.

The code should be self-explanatory with some comments about implementation choices. If you still have questions, feel free to ask, and I will be glad to answer.

I have included a breadcrumb instead of only a "go up" button, but I can change it.

Good review!

### CODE REVIEW

**Comment by jpagex** [comment]
READY

**Comment by gnikolaropoulos** [comment]
Hello mate! I am one of the Engineering managers of GWI. We are currently on budget discussions about our next fiscal year so we are not sure how many (if any) open positions we will have. I have to thank you very much for your effort and for your interest. If we do get an opening I ll make sure that we provide you some proper feedback! Take care and keep up the good work!

**Comment by gnikolaropoulos** [comment]
@jpagex are you maybe still looking for future opportunities?

**Comment by jpagex** [comment]
@gnikolaropoulos Hi! Thanks for asking, but I am not looking for a new opportunity at the moment. Take care!

**Pull request closed without merging**
