### PR TITLE
Thanks for such a great challenge

### PR DESCRIPTION
**Pull request by kraklin**
This was really fun. I have finally an excuse to try JSON decoders and even try to implement my own tree structure in Elm. I learn a few tricks studying another tree implementations and decode my first JSON in Elm  😃 

I didn't bother with nice GUI, because I wanted to keep things simple and runnable with elm reactor, so there are no CSS or other features, just plain HTML and lists.

Anyway - Thanks 👍

### CODE REVIEW

**Comment by turboMaCk** [comment]
hey @kraklin I'm glad you've enjoyed hacking on this!

I'll review your code later to give you some feedback. We don't really care about UI look that much in case of challenges like this so don't worry. For now just:

**Comment by kraklin** [comment]
Sure, take your time. I'm looking forward to your ideas and suggestions ;)

**Comment by Janiczek** [comment]
@kraklin a piece of history, isn't it :smile:

**Comment by kraklin** [comment]
Yup, I have been cleaning of stale branches :) But yeah, nostalgic as hell :D and it has been "only" 3 years

**Pull request closed without merging**
